### ISSUE TITLE
Do not react to touch events outside of polylines

### ISSUE THREAD

**Issue by tuarrep** [OwnWeb/flutter_map_tappable_polyline#7]
As gesture detection works nowadays zooming the underlying map is impossible with double tapping because this gesture is filtered by the package's `GestureDetector` https://github.com/OwnWeb/flutter_map_tappable_polyline/blob/1dd7bc8c2a1fc779da986b6a7ae415d45e710aae/lib/flutter_map_tappable_polyline.dart#L100

More globally all touch events are catched even outside of polylines because the layer take all screen, and, then, react to touch events on all screen.

**Comment by Mkohm** [comment]
Any ideas for solving this issue? Can we detect double taps with the current gesture detector, and control the zoom of the map that way?

Or is there any way we can preserve the original map behavior?

**Comment by tuarrep** [comment]
> Can we detect double taps with the current gesture detector  

Yes

> and control the zoom of the map that way

Nope

I've tried an implementation here f606d5832f57e2396096c91e87fc3e634d316df8 but it appears to break onTap callback

**Comment by bongio94** [comment]
Hello everyone! I am facing the same problem described in this issue. I've tried to mess around with the plugin code and found that if you use onLongPressEnd instead of onTapUp inside the GestureDetector the map will work as expected (double tap to zoom is working). Of course it changes the behaviour of the plugin, (if you have another gesture on you map that uses the long press action this may not work) but in my case I can live with the long press on the polyline and not loose the double tap to zoom gesture! Hope this can be useful to others!

**Comment by tuarrep** [comment]
Thanks, @bongio94!

As you said, your workaround changes the behaviour and the purpose of this package. So I'll never merge something like this.
BTW do not hesitate to fork and share your version here for further reference.

**Comment by tuarrep** [comment]
Fixed in #12
